services:
  postgres:
    image: postgres
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./DB/postgres_data:/var/lib/postgresql/data
  pgadmin4:
    image: elestio/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    volumes:
       - ./DB/pgadmin_data:/var/lib/pgadmin  
       - ./DB/servers.json:/pgadmin4/servers.json